name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build --no-cache
    #- name: Up Container
    #  run: docker-compose up -d
    #- name: Exec Container
    #  run: docker-compose exec --no-TTY app bash
    - name: Run pylint test with Docker Container
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: addnab/docker-run-action@v3
      with:
          image: selenium-test_app:latest
          options: -v ${{ github.workspace }}:/var/www
          run: |
              pip install pylint
              apt-get -y update && apt install -y curl
              curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s \
              && mv ./bin/reviewdog /usr/local/bin \
              && rm -rf ./bin/reviewdog \
              && pylint src/ | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review